[package]
name = "simple-server"
version = "0.1.0"
authors = ["shahirZain <shahirzain100@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple-server = "0.4.0"
